//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginPagePeoject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class proteckhydbEntities : DbContext
    {
        public proteckhydbEntities()
            : base("name=proteckhydbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<loginpage> loginpages { get; set; }
        public virtual DbSet<DesignTb> DesignTbs { get; set; }
        public virtual DbSet<registration> registrations { get; set; }
    }
}
