//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginPagePeoject
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromoteEmployee
    {
        public int ID { get; set; }
        public Nullable<int> Designation { get; set; }
        public Nullable<int> SelectEmployee { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<int> AssignTo { get; set; }
        public Nullable<int> NewDesignation { get; set; }
        public Nullable<int> NewSupervisor { get; set; }
    
        public virtual DesignTb DesignTb { get; set; }
        public virtual EmployeeDetail EmployeeDetail { get; set; }
        public virtual DesignTb DesignTb1 { get; set; }
        public virtual EmployeeDetail EmployeeDetail1 { get; set; }
        public virtual EmployeeDetail EmployeeDetail11 { get; set; }
    }
}
